/**
 * @apiDefine WebhookTrigger
 * @apiParam  {String} action Webhook action identifying the purpose of this request.
 */
export enum WebhookTrigger {
  TITLE_CREATE = 'TITLE_CREATE',
  TITLE_DELETE = 'TITLE_DELETE',

  BRANCH_CREATE = 'BRANCH_CREATE',
  BRANCH_MODIFY = 'BRANCH_MODIFY',
  BRANCH_DELETE = 'BRANCH_DELETE',

  BUILD_CREATE = 'BUILD_CREATE',
  // BUILD_MODIFY = 'BUILD_MODIFY',

  BUILD_DELETE = 'BUILD_DELETE',
  DEPOT_CREATE = 'DEPOT_CREATE',
  DEPOT_MODIFY = 'DEPOT_MODIFY',

  REDISTRIBUTABLE_CREATE = 'REDISTRIBUTABLE_CREATE',
  REDISTRIBUTABLE_MODIFY = 'REDISTRIBUTABLE_MODIFY',

  /* LAUNCH_OPTIONS_CREATE = 'LAUNCH_OPTIONS_CREATE',
  LAUNCH_OPTIONS_MODIFY = 'LAUNCH_OPTIONS_MODIFY',
  LAUNCH_OPTIONS_DELETE = 'LAUNCH_OPTIONS_DELETE', */

  WEBHOOKS_CREATE = 'WEBHOOKS_CREATE',
  WEBHOOKS_DELETE = 'WEBHOOKS_DELETE',
  WEBHOOKS_READ = 'WEBHOOKS_READ',

  READ = 'READ',
}

export const triggersModifyRedistributable = [
  WebhookTrigger.REDISTRIBUTABLE_CREATE,
  WebhookTrigger.REDISTRIBUTABLE_MODIFY,
];

export const triggersWebhooks = [
  WebhookTrigger.WEBHOOKS_CREATE,
  WebhookTrigger.WEBHOOKS_READ,
  WebhookTrigger.WEBHOOKS_DELETE,
];
