ingresses:
  - scheme: internet-facing
    security_groups:
      - eks-alb
      - cloudflare
      - ghost-inspector
      - corp
      - eip # allow all access from our d2c vpc. Should be removed once BDS is migrated to flux
    external_to_vpc_sgs:
      - mpg_2k_bds
      - eks-debugging-alb