name: develop

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com/"
          scope: take-two-t2gp
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.T2GP_BUILD_TOKEN }}
      - run: npm run lint
      - run: npm run test
  docker:
    name: Build docker image
    needs: test
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: take-two-t2gp
      - name: Gen build info
        run: |
          echo VER=$(git rev-parse --short=8 ${{ github.sha }}) >> $GITHUB_ENV          
      - name: build image
        run: |
          docker build -t t2gp-publisher-service --build-arg NPM_TOKEN="${{ secrets.T2GP_BUILD_TOKEN }}" .
      - name: push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: t2gp-publisher-service
          image: t2gp-publisher-service:${{ env.VER }}
      - name: clean up
        run: docker image prune -a --force --filter "until=48h"
  k8s-deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: docker
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: us-east-1
    steps:
      # Deploy status
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment: develop
          ref: ${{ github.sha }}
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Gen build info
        run: |
          echo VER=$(git rev-parse --short=8 ${{ github.sha }}) >> $GITHUB_ENV  
          REF=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          # TODO: Once production cluster is setup, move production over to new cluster
          CLUSTER=t2gp-flux
          echo "BRANCH=$REF" >> $GITHUB_ENV
          echo "CLUSTER=$CLUSTER" >> $GITHUB_ENV   
      - name: Authenticate to EKS Cluster
        run: |
          echo KUBETOKEN=$(aws eks get-token --cluster-name ${{ env.CLUSTER }} --region ${{ env.REGION }} | jq -r '.status.token') >> $GITHUB_ENV
          echo CLUSTER_ENDPOINT=$(aws eks describe-cluster --name ${{ env.CLUSTER }} --region ${{ env.REGION }} | jq -r '.cluster.endpoint') >> $GITHUB_ENV
      
      - name: Deploy Helm Chart
        uses: nmasur/alpine-kubectl@master
        with:
          command: |-
            kubectl config set-cluster cluster \
              --server=${{ env.CLUSTER_ENDPOINT }} \
              --insecure-skip-tls-verify && \
            kubectl config set-context cluster \
              --cluster=cluster && \
            kubectl config use-context cluster && \
            helm upgrade --install \
              publisher-service-${{ env.BRANCH }} /github/workspace/helm_chart \
              --kube-token=${{ env.KUBETOKEN }} \
              --create-namespace \
              -n publisher-service \
              -f /github/workspace/helm_values/${{ env.BRANCH }}.yaml \
              --set app.tag=${{ env.VER }} \
              --set app.name=publisher
            helm upgrade --install \
              downloader-service-${{ env.BRANCH }} /github/workspace/helm_chart \
              --kube-token=${{ env.KUBETOKEN }} \
              --create-namespace \
              -n publisher-service \
              -f /github/workspace/helm_values/${{ env.BRANCH }}.yaml \
              --set app.tag=${{ env.VER }} \
              --set app.name=downloader
        # Update deployment status
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  docs:
    name: "publish develop docs"

    runs-on: [self-hosted, linux]

    needs: test

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg/github.com/"
          scope: take-two-t2gp
      - name: "Install dependencies"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_BUILD_TOKEN }}
        run: npm ci
      - name: "document generation"
        run: npm run doc
      - name: "sync to S3"
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: t2gp-documentation
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"
          SOURCE_DIR: "docs"
          DEST_DIR: "t2gp-publisher-service/develop"
