on:
  push:
    branches:
      - develop

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test run
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cluster: t2gp-debugging
          dry-run: true
          namespace: cicd-test
          release-name: helm-deploy-test
          chart-location: helm_chart
          value-files: helm_values/test_values.yml
          values: replicaCount=2
      - name: Get output
        run: |
          echo "${{ steps.test.outputs.results }}"